### ISSUE TITLE
Eclipse Tycho: Missing vgwort

### ISSUE THREAD

**Issue by fap-** [vogellacompany/com.vogella.tutorials.eclipse#4]
`asciidoctor: WARNING: dropping line containing reference to missing attribute: vgwort`

![selection_034](https://cloud.githubusercontent.com/assets/459631/20786670/a4f14820-b7a7-11e6-8e69-fa50796f4787.png)

**Comment by vogella** [comment]
Would that be caught by our 0.5.1 plugin?

Am 01.12.2016 9:22 vorm. schrieb "FAP" <notifications@github.com>:

**Comment by fap-** [comment]
No, this is a warning that isn't included yet. Should I add it?

**Comment by vogella** [comment]
+1

Am 01.12.2016 9:26 vorm. schrieb "FAP" <notifications@github.com>:

**Comment by jnerlich** [comment]
Could you please send me the name of the tutorial ? 


Von meinem Samsung Gerät gesendet.

-------- Ursprüngliche Nachricht --------
Von: FAP <notifications@github.com> 
Datum: 01.12.2016  09:22  (GMT+01:00) 
An: "vogellacompany/com.vogella.tutorials.eclipse" <com.vogella.tutorials.eclipse@noreply.github.com> 
Cc: Jennifer Nerlich <jennifer.nerlich@vogella.com>, Assign <assign@noreply.github.com> 
Betreff: [vogellacompany/com.vogella.tutorials.eclipse] Eclipse Tycho: Missing
  vgwort (#4) 

asciidoctor: WARNING: dropping line containing reference to missing attribute: vgwort


—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/vogellacompany/com.vogella.tutorials.eclipse","title":"vogellacompany/com.vogella.tutorials.eclipse","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/vogellacompany/com.vogella.tutorials.eclipse"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Eclipse Tycho: Missing vgwort (#4)"}],"action":{"name":"View Issue","url":"https://github.com/vogellacompany/com.vogella.tutorials.eclipse/issues/4"}}}

**Comment by vogella** [comment]
See issue header: EclipseTycho

Am 01.12.2016 9:33 vorm. schrieb "Jennifer Nerlich" <
notifications@github.com>:

**Comment by fap-** [comment]
https://github.com/vogellacompany/com.vogella.tutorials.eclipse/tree/master/EclipseTycho

**Comment by fap-** [comment]
After this issue is closed we can push the plugin version to 0.5.2

**Comment by jnerlich** [comment]
The problem was not a missing vgwort, but the fact, that the tutorial title was defined with a == instead of =.
Issue fixed now.
